// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4Tifo6crQ_k44LvrPvd2-BX2Q31_Dk28',
    appId: '1:754585659227:web:44e0395ca7ce73c9239c7e',
    messagingSenderId: '754585659227',
    projectId: 'cinema-city-app',
    authDomain: 'cinema-city-app.firebaseapp.com',
    storageBucket: 'cinema-city-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8a0QpmxShTgtY7pm-fA-IqKi6zjjM4sw',
    appId: '1:754585659227:android:8e0f6934ded2e1a9239c7e',
    messagingSenderId: '754585659227',
    projectId: 'cinema-city-app',
    storageBucket: 'cinema-city-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNE161TQVtmrnAaKDTGRj6kEf0WUBPXlk',
    appId: '1:754585659227:ios:e3ee6b0555dcfa26239c7e',
    messagingSenderId: '754585659227',
    projectId: 'cinema-city-app',
    storageBucket: 'cinema-city-app.firebasestorage.app',
    iosBundleId: 'com.example.dribbleCinemaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4Tifo6crQ_k44LvrPvd2-BX2Q31_Dk28',
    appId: '1:754585659227:web:da4e43a34c3b9ac1239c7e',
    messagingSenderId: '754585659227',
    projectId: 'cinema-city-app',
    authDomain: 'cinema-city-app.firebaseapp.com',
    storageBucket: 'cinema-city-app.firebasestorage.app',
  );
}
